name: torch-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - pandas_ml
  - pip
  - graphviz
  - pydotplus
  - torchvision
